### ISSUE TITLE
Is there a reason there's no "mention_from" edge?

### ISSUE THREAD

**Issue by williamgunn** [seinecle/gephi-tutorials#10]
This is a question about why you modeled the interactions the way they're modeled.

You have the following user edges:
user - (tweets) -> tweet
user - (retweets) -tweet
user - (quotes) -> tweet
user - (has_retweet_from) -> user
user - (has_quote_from) -> user

It seems like there should also be a 
user - (has_mention_from) -> user edge, but you only have a 
tweet - (has_mention_of) -> user edge

Is there something I'm missing or did you just not feel the need for this relationship?

**Comment by seinecle** [comment]
Sorry for this late reply. The developer and maintainer of this plugin is Matthieu Totet, who can answer you (https://twitter.com/Totetmatt)
