### ISSUE TITLE
Image broken text Twitter Streaming Importer

### ISSUE THREAD

**Issue by csantanaes** [seinecle/gephi-tutorials#32]
many imagens broken: 
https://github.com/seinecle/gephi-tutorials/blob/master/src/main/asciidoc/en/plugins/twitter-streaming-importer-en.adoc

![image](https://user-images.githubusercontent.com/7091412/137657574-49ddabde-4b3e-4f24-be70-99e617485d43.png)

![image](https://user-images.githubusercontent.com/7091412/137657613-ba006561-ebf9-4d76-a38f-3e9fbc892230.png)

![image](https://user-images.githubusercontent.com/7091412/137657679-c70b725e-b1fb-405d-8bfd-34712d954a28.png)

![image](https://user-images.githubusercontent.com/7091412/137657706-1bd7a819-1658-41cf-b4fd-b3b31ef45e88.png)

**Comment by seinecle** [comment]
Hi,
Thank you for this alert and sorry for the late response. I have reviewed the tutorials and they are now up to date:
https://seinecle.github.io/gephi-tutorials/
