### ISSUE TITLE
The plugin isn't working

### ISSUE THREAD

**Issue by b-codex** [seinecle/gephi-tutorials#36]
I am trying to send a request with some filters on Gephi and I am getting the error below. Since I'm new to this, I need some help in fixing this.

403:The request is understood, but it has been refused. An accompanying error message will explain why. This code is used when requests are being denied due to update limits (https://support.twitter.com/articles/15364-about-twitter-limits-update-api-dm-and-following).

![image](https://user-images.githubusercontent.com/61845339/168476657-ae46f088-0b9d-4f5a-b925-4490f0b232fb.png)

**Comment by seinecle** [comment]
Hi, 
I am not the developer of the Twitter importer plugin. Please check this answer / comment from the developer:
https://github.com/gephi/gephi/discussions/2530#discussioncomment-2738591
