### ISSUE TITLE
Any way to get the actual tweets using User Network in Twitter Streaming Importer?

### ISSUE THREAD

**Issue by dhsdshdhk** [seinecle/gephi-tutorials#9]
Using the User Network, the edges connecting different users do not contain the tweet's text, only information such as source, target and whether it is a mention, retweet or quote.

Is it possible to get the text somehow? I think it would be pretty simple to patch the plugin to add that functionality.

**Comment by seinecle** [comment]
Sorry for this late reply. The developer and maintainer of this plugin is Matthieu Totet, who can answer you (https://twitter.com/Totetmatt)
